# Generated by Django 4.1 on 2023-10-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_cook_photo_alter_dish_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='photo',
            field=models.ImageField(default='photos/cooks/default.jpg', upload_to='photos/cooks'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default='photos/dishes/default.jpg', upload_to='photos/dishes'),
        ),
    ]
